//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace NSCC.Web.Awards.DataAccess.Service1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CurrentProgramsSoap", Namespace="http://tempuri.org/")]
    public partial class CurrentPrograms : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllCampusesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampusByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProgramsForPreviousYearOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampusesForProgramOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProgramByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCampusMappingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllProgramsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CurrentPrograms() {
            this.Url = global::NSCC.Web.Awards.DataAccess.Properties.Settings.Default.NSCC_Web_Awards_DataAccess_Service1_CurrentPrograms;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllCampusesCompletedEventHandler GetAllCampusesCompleted;
        
        /// <remarks/>
        public event GetCampusByIdCompletedEventHandler GetCampusByIdCompleted;
        
        /// <remarks/>
        public event GetProgramsForPreviousYearCompletedEventHandler GetProgramsForPreviousYearCompleted;
        
        /// <remarks/>
        public event GetCampusesForProgramCompletedEventHandler GetCampusesForProgramCompleted;
        
        /// <remarks/>
        public event GetProgramByIdCompletedEventHandler GetProgramByIdCompleted;
        
        /// <remarks/>
        public event GetCampusMappingsCompletedEventHandler GetCampusMappingsCompleted;
        
        /// <remarks/>
        public event GetAllProgramsCompletedEventHandler GetAllProgramsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCampuses", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Campus[] GetAllCampuses(int programId) {
            object[] results = this.Invoke("GetAllCampuses", new object[] {
                        programId});
            return ((Campus[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCampusesAsync(int programId) {
            this.GetAllCampusesAsync(programId, null);
        }
        
        /// <remarks/>
        public void GetAllCampusesAsync(int programId, object userState) {
            if ((this.GetAllCampusesOperationCompleted == null)) {
                this.GetAllCampusesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCampusesOperationCompleted);
            }
            this.InvokeAsync("GetAllCampuses", new object[] {
                        programId}, this.GetAllCampusesOperationCompleted, userState);
        }
        
        private void OnGetAllCampusesOperationCompleted(object arg) {
            if ((this.GetAllCampusesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCampusesCompleted(this, new GetAllCampusesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCampusById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Campus[] GetCampusById(string campusCode) {
            object[] results = this.Invoke("GetCampusById", new object[] {
                        campusCode});
            return ((Campus[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCampusByIdAsync(string campusCode) {
            this.GetCampusByIdAsync(campusCode, null);
        }
        
        /// <remarks/>
        public void GetCampusByIdAsync(string campusCode, object userState) {
            if ((this.GetCampusByIdOperationCompleted == null)) {
                this.GetCampusByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampusByIdOperationCompleted);
            }
            this.InvokeAsync("GetCampusById", new object[] {
                        campusCode}, this.GetCampusByIdOperationCompleted, userState);
        }
        
        private void OnGetCampusByIdOperationCompleted(object arg) {
            if ((this.GetCampusByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampusByIdCompleted(this, new GetCampusByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProgramsForPreviousYear", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Program[] GetProgramsForPreviousYear(string substring, string campusCode) {
            object[] results = this.Invoke("GetProgramsForPreviousYear", new object[] {
                        substring,
                        campusCode});
            return ((Program[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProgramsForPreviousYearAsync(string substring, string campusCode) {
            this.GetProgramsForPreviousYearAsync(substring, campusCode, null);
        }
        
        /// <remarks/>
        public void GetProgramsForPreviousYearAsync(string substring, string campusCode, object userState) {
            if ((this.GetProgramsForPreviousYearOperationCompleted == null)) {
                this.GetProgramsForPreviousYearOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProgramsForPreviousYearOperationCompleted);
            }
            this.InvokeAsync("GetProgramsForPreviousYear", new object[] {
                        substring,
                        campusCode}, this.GetProgramsForPreviousYearOperationCompleted, userState);
        }
        
        private void OnGetProgramsForPreviousYearOperationCompleted(object arg) {
            if ((this.GetProgramsForPreviousYearCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProgramsForPreviousYearCompleted(this, new GetProgramsForPreviousYearCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCampusesForProgram", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Campus[] GetCampusesForProgram(string programCode) {
            object[] results = this.Invoke("GetCampusesForProgram", new object[] {
                        programCode});
            return ((Campus[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCampusesForProgramAsync(string programCode) {
            this.GetCampusesForProgramAsync(programCode, null);
        }
        
        /// <remarks/>
        public void GetCampusesForProgramAsync(string programCode, object userState) {
            if ((this.GetCampusesForProgramOperationCompleted == null)) {
                this.GetCampusesForProgramOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampusesForProgramOperationCompleted);
            }
            this.InvokeAsync("GetCampusesForProgram", new object[] {
                        programCode}, this.GetCampusesForProgramOperationCompleted, userState);
        }
        
        private void OnGetCampusesForProgramOperationCompleted(object arg) {
            if ((this.GetCampusesForProgramCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampusesForProgramCompleted(this, new GetCampusesForProgramCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetProgramById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Program[] GetProgramById(string programCode) {
            object[] results = this.Invoke("GetProgramById", new object[] {
                        programCode});
            return ((Program[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProgramByIdAsync(string programCode) {
            this.GetProgramByIdAsync(programCode, null);
        }
        
        /// <remarks/>
        public void GetProgramByIdAsync(string programCode, object userState) {
            if ((this.GetProgramByIdOperationCompleted == null)) {
                this.GetProgramByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProgramByIdOperationCompleted);
            }
            this.InvokeAsync("GetProgramById", new object[] {
                        programCode}, this.GetProgramByIdOperationCompleted, userState);
        }
        
        private void OnGetProgramByIdOperationCompleted(object arg) {
            if ((this.GetProgramByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProgramByIdCompleted(this, new GetProgramByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCampusMappings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CampusMapping[] GetCampusMappings() {
            object[] results = this.Invoke("GetCampusMappings", new object[0]);
            return ((CampusMapping[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCampusMappingsAsync() {
            this.GetCampusMappingsAsync(null);
        }
        
        /// <remarks/>
        public void GetCampusMappingsAsync(object userState) {
            if ((this.GetCampusMappingsOperationCompleted == null)) {
                this.GetCampusMappingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCampusMappingsOperationCompleted);
            }
            this.InvokeAsync("GetCampusMappings", new object[0], this.GetCampusMappingsOperationCompleted, userState);
        }
        
        private void OnGetCampusMappingsOperationCompleted(object arg) {
            if ((this.GetCampusMappingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCampusMappingsCompleted(this, new GetCampusMappingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllPrograms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Program[] GetAllPrograms(string substring, string campusCode) {
            object[] results = this.Invoke("GetAllPrograms", new object[] {
                        substring,
                        campusCode});
            return ((Program[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllProgramsAsync(string substring, string campusCode) {
            this.GetAllProgramsAsync(substring, campusCode, null);
        }
        
        /// <remarks/>
        public void GetAllProgramsAsync(string substring, string campusCode, object userState) {
            if ((this.GetAllProgramsOperationCompleted == null)) {
                this.GetAllProgramsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllProgramsOperationCompleted);
            }
            this.InvokeAsync("GetAllPrograms", new object[] {
                        substring,
                        campusCode}, this.GetAllProgramsOperationCompleted, userState);
        }
        
        private void OnGetAllProgramsOperationCompleted(object arg) {
            if ((this.GetAllProgramsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllProgramsCompleted(this, new GetAllProgramsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Campus {
        
        private string campusCodeField;
        
        private string campusDescrField;
        
        private string locationField;
        
        /// <remarks/>
        public string CampusCode {
            get {
                return this.campusCodeField;
            }
            set {
                this.campusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CampusDescr {
            get {
                return this.campusDescrField;
            }
            set {
                this.campusDescrField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CampusMapping {
        
        private string campusCodeField;
        
        private string programCodeField;
        
        private string actualCampusCodeField;
        
        /// <remarks/>
        public string CampusCode {
            get {
                return this.campusCodeField;
            }
            set {
                this.campusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProgramCode {
            get {
                return this.programCodeField;
            }
            set {
                this.programCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ActualCampusCode {
            get {
                return this.actualCampusCodeField;
            }
            set {
                this.actualCampusCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Program {
        
        private string programCodeField;
        
        private string programDescrField;
        
        private Campus[] campusesField;
        
        /// <remarks/>
        public string ProgramCode {
            get {
                return this.programCodeField;
            }
            set {
                this.programCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProgramDescr {
            get {
                return this.programDescrField;
            }
            set {
                this.programDescrField = value;
            }
        }
        
        /// <remarks/>
        public Campus[] Campuses {
            get {
                return this.campusesField;
            }
            set {
                this.campusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllCampusesCompletedEventHandler(object sender, GetAllCampusesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCampusesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCampusesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Campus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Campus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCampusByIdCompletedEventHandler(object sender, GetCampusByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampusByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampusByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Campus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Campus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProgramsForPreviousYearCompletedEventHandler(object sender, GetProgramsForPreviousYearCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProgramsForPreviousYearCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProgramsForPreviousYearCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Program[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Program[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCampusesForProgramCompletedEventHandler(object sender, GetCampusesForProgramCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampusesForProgramCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampusesForProgramCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Campus[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Campus[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProgramByIdCompletedEventHandler(object sender, GetProgramByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProgramByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProgramByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Program[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Program[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCampusMappingsCompletedEventHandler(object sender, GetCampusMappingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCampusMappingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCampusMappingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CampusMapping[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CampusMapping[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllProgramsCompletedEventHandler(object sender, GetAllProgramsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllProgramsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllProgramsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Program[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Program[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591